from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


def generate_pdf(ip, open_ports, closed_ports, scan_time, results):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer, pagesize=letter)

    styles = getSampleStyleSheet()

    elements = []

    title = Paragraph("<b><font size=20>Cyber Port Scanner Report</font></b>", styles["Title"])

    elements.append(title)

    elements.append(Spacer(1,20))

    info = [

        ["Target IP", ip],

        ["Open Ports", str(open_ports)],

        ["Closed Ports", str(closed_ports)],

        ["Scan Time", scan_time]

    ]

    info_table = Table(info, colWidths=[150,300])

    info_table.setStyle(TableStyle([

        ("GRID",(0,0),(-1,-1),1,colors.black),

        ("BACKGROUND",(0,0),(0,-1),colors.lightblue),

        ("FONTNAME",(0,0),(-1,-1),"Helvetica-Bold"),

        ("BOTTOMPADDING",(0,0),(-1,-1),10)

    ]))

    elements.append(info_table)

    elements.append(Spacer(1,25))
    table_data = [

        ["Port", "Service", "Status"]

    ]

    for item in results:

        if item["service"] == "No Standard Service":
            continue

        table_data.append([

            str(item["port"]),

            item["service"],

            item["status"]

        ])

    results_table = Table(

        table_data,

        colWidths=[80, 250, 120]

    )

    results_table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("ALIGN", (0, 0), (-1, -1), "CENTER"),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("GRID", (0, 0), (-1, -1), 1, colors.black),

        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

    ]))

    for row in range(1, len(table_data)):

        status = table_data[row][2]

        if status == "Open":

            results_table.setStyle(TableStyle([

                ("TEXTCOLOR", (2, row), (2, row), colors.green)

            ]))

        else:

            results_table.setStyle(TableStyle([

                ("TEXTCOLOR", (2, row), (2, row), colors.red)

            ]))

    elements.append(results_table)

    elements.append(Spacer(1, 25))
    footer = Paragraph(
        "<br/><br/><b>Generated by:</b> Cyber Port Scanner"
        "<br/><b>Developed by:</b> Satyam Savita",
        styles["Normal"]
    )

    elements.append(footer)

    doc.build(elements)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf